# Use Python official image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy script into the container
COPY ./line_counter.py .

# Define entry point
ENTRYPOINT ["python", "line_counter.py"]
